"""Added vote table.

Revision ID: e888908bfa01
Revises: 
Create Date: 2021-05-30 23:58:57.184954

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e888908bfa01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('electionOfficialJmbg', sa.String(length=256), nullable=False),
    sa.Column('ballotGuid', sa.String(length=256), nullable=False),
    sa.Column('pollNumber', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=256), nullable=True),
    sa.Column('electionId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['electionId'], ['elections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ballotGuid')
    )
    op.alter_column('electionparticipants', 'pollNumber',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('electionparticipants', 'pollNumber',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_table('votes')
    # ### end Alembic commands ###
